let challenge ='30 Days Of JavaScript'
console.log(challenge)
console.log(challenge.length)
console.log(challenge.toUpperCase())
console.log(challenge.toLowerCase())
console.log(challenge.substr(3))
console.log(challenge.substr(0, 3))
console.log(challenge.includes('Script'))
console.log(challenge.split())
console.log(challenge.split(' '))
let challenge1 ='30, Days, Of, JavaScript'
console.log(challenge1.split(','))
console.log(challenge.replace('JavaScript', 'Python'))
console.log(challenge.charAt(15))
console.log(challenge.indexOf('J'))
let inJ =challenge.indexOf('J')
console.log(challenge.charCodeAt(inJ))
console.log(challenge.indexOf('a'))
console.log(challenge.lastIndexOf('a'))
console.log('You cannot end a sentence with because because because is a conjunction'.indexOf('because'))
console.log('You cannot end a sentence with because because because is a conjunction'.lastIndexOf('because'))
console.log('You cannot end a sentence with because because because is a conjunction'.search('because'))
console.log(' 30 Days Of JavaScript '.trim())
console.log('30 Days Of JavaScript '.startsWith('30'))
console.log('30 Days Of JavaScript'.endsWith('JavaScript'))
console.log(challenge.match('a'))
let first ='30 Days Of'
console.log(first.concat("JavaScript")) 
console.log(challenge.repeat(2))